import universityBasicDetailsSlice,{universityBasicDetailsReducer,universityBasicDetailsUpdateReducer} from './universityBasicDetails'
import universityContactSlice,{universityContactReducer,universityContactAddReducer,universityContactUpdateReducer} from './universityContactPerson'
import universityMeetingSlice,{universityMeetingReducer,universityMeetingAddReducer,universityMeetingUpdateReducer} from './universityMeeting'
import universityProgramSlice,{universityProgramReducer,universityProgramAddReducer} from './universityProgram'
import universityRecentUpdateSlice,{universityRecentUpdateReducer,universityRecentUpdateAddReducer,universityRecentUpdateUpdateReducer} from './universityRecentUpdates'
import universityMouContractSlice,{universityMouContractReducer,universityMouContractAddReducer,universityMouContractUpdateReducer,setMouContractSliceLoading} from './universityMouContract'
import universityApplicationProcessSlice,{universityApplicationProcessReducer,universityApplicationProcessAddReducer} from './universityApplicationProcess'
import universityDocumentRequiredSlice,{universityDocumentRequiredReducer,universityDocumentRequiredAddReducer} from './universityDocumentRequired'
import universityFinancialAgreementSlice,{universityFinancialAgreementReducer,universityFinancialAgreementAddReducer,} from './universityFinancialAgreement'
import universityGuestVisitSlice,{universityGuestVisitReducer,universityGuestVisitAddReducer} from './universityGuestVisit'
import getAllUniversitySlice, {getAllUniversityReducer,setRedirectFunction,updateViewDetails,universityAddReducer} from './getAllUniversity'
import tagsMouMasterSlice, {activateYourTagChip,deleteYourTagChip,addYourTagChip} from './tags'

export {
	universityBasicDetailsSlice,universityBasicDetailsReducer,universityBasicDetailsUpdateReducer,
	universityContactSlice,universityContactReducer,universityContactAddReducer,universityContactUpdateReducer,
	universityMeetingSlice,universityMeetingReducer,universityMeetingAddReducer,universityMeetingUpdateReducer,
	universityProgramSlice,universityProgramReducer,universityProgramAddReducer,
	universityRecentUpdateSlice,universityRecentUpdateReducer,universityRecentUpdateAddReducer,universityRecentUpdateUpdateReducer,
	universityMouContractSlice,universityMouContractReducer,universityMouContractAddReducer,universityMouContractUpdateReducer,setMouContractSliceLoading,
	universityApplicationProcessSlice,universityApplicationProcessReducer,universityApplicationProcessAddReducer,
	universityDocumentRequiredSlice,universityDocumentRequiredReducer,universityDocumentRequiredAddReducer,
	universityFinancialAgreementReducer,universityFinancialAgreementAddReducer,universityFinancialAgreementSlice,
	universityGuestVisitSlice,universityGuestVisitReducer,universityGuestVisitAddReducer,
	getAllUniversitySlice,getAllUniversityReducer,setRedirectFunction,updateViewDetails,universityAddReducer,

	tagsMouMasterSlice,activateYourTagChip,deleteYourTagChip,addYourTagChip,

}