import universityBasicDetailsSlice,{universityBasicDetailsReducer,universityBasicDetailsUpdateReducer} from './universityBasicDetails'
import universityContactSlice,{universityContactReducer,universityContactAddReducer} from './universityContactPerson'
import universityMeetingSlice,{universityMeetingReducer,universityMeetingAddReducer,universityMeetingUpdateReducer} from './universityMeeting'
import universityProgramSlice,{universityProgramReducer,universityProgramAddReducer} from './universityProgram'
import universityRecentUpdateSlice,{universityRecentUpdateReducer,universityRecentUpdateAddReducer} from './universityRecentUpdates'
import universityMouContractSlice,{universityMouContractReducer,universityMouContractAddReducer,universityMouContractUpdateReducer} from './universityMouContract'


export {
	universityBasicDetailsSlice,universityBasicDetailsReducer,universityBasicDetailsUpdateReducer,
	universityContactSlice,universityContactReducer,universityContactAddReducer,
	universityMeetingSlice,universityMeetingReducer,universityMeetingAddReducer,universityMeetingUpdateReducer,
	universityProgramSlice,universityProgramReducer,universityProgramAddReducer,
	universityRecentUpdateSlice,universityRecentUpdateReducer,universityRecentUpdateAddReducer,
	universityMouContractSlice,universityMouContractReducer,universityMouContractAddReducer,universityMouContractUpdateReducer,
}