import universityBasicDetailsSlice,{universityBasicDetailsReducer,universityBasicDetailsUpdateReducer} from './universityBasicDetails'
import universityContactSlice,{universityContactReducer,universityContactAddReducer,universityContactUpdateReducer} from './universityContactPerson'
import universityMeetingSlice,{universityMeetingReducer,universityMeetingAddReducer,universityMeetingUpdateReducer} from './universityMeeting'
import universityProgramSlice,{universityProgramReducer,universityProgramAddReducer} from './universityProgram'
import universityRecentUpdateSlice,{universityRecentUpdateReducer,universityRecentUpdateAddReducer} from './universityRecentUpdates'


export {
	universityBasicDetailsSlice,universityBasicDetailsReducer,universityBasicDetailsUpdateReducer,
	universityContactSlice,universityContactReducer,universityContactAddReducer,universityContactUpdateReducer,
	universityMeetingSlice,universityMeetingReducer,universityMeetingAddReducer,universityMeetingUpdateReducer,
	universityProgramSlice,universityProgramReducer,universityProgramAddReducer,
	universityRecentUpdateSlice,universityRecentUpdateReducer,universityRecentUpdateAddReducer,
}