import {
	universityBasicDetailsSlice,universityBasicDetailsReducer,universityBasicDetailsUpdateReducer,
	universityContactSlice,universityContactReducer,universityContactAddReducer,universityContactUpdateReducer,
	universityMeetingSlice,universityMeetingReducer,universityMeetingAddReducer,universityMeetingUpdateReducer,
	universityProgramSlice,universityProgramReducer,universityProgramAddReducer,
	universityRecentUpdateSlice,universityRecentUpdateReducer,universityRecentUpdateAddReducer,universityRecentUpdateUpdateReducer,
	universityMouContractSlice,universityMouContractReducer,universityMouContractAddReducer,universityMouContractUpdateReducer,setMouContractSliceLoading,
	universityApplicationProcessSlice,universityApplicationProcessReducer,universityApplicationProcessAddReducer,
	universityDocumentRequiredSlice,universityDocumentRequiredReducer,universityDocumentRequiredAddReducer,
	universityFinancialAgreementReducer,universityFinancialAgreementAddReducer,universityFinancialAgreementSlice,
	universityGuestVisitSlice,universityGuestVisitReducer,universityGuestVisitAddReducer,
	getAllUniversitySlice,getAllUniversityReducer,setRedirectFunction,updateViewDetails,universityAddReducer,

	tagsMouMasterSlice,activateYourTagChip,deleteYourTagChip,addYourTagChip,
} from './university/routes'

import {
	forgetPasswordSlice,forgetPasswordReducer,resetPasswordReducer,
} from './users/routes'

import {
	getAllMeetingsSlice,	
	getAllUniversityMeetingsReducer,universityMeetingsAddReducer,setRedirectFunctionMeetings,updateViewDetailsMeetings,
	getMeetingsSlice,getMeetingsReducer,meetingBasicDetailsUpdateReducer,
} from './meeting/routes'


import {
	basicGuestVisitSlice,getAllGuestVisitReducer,guestVisitAddReducer,
	setRedirectFunctionGuestVisit,updateViewDetailsGuestVisit,
	singleGuestVisitSlice,getGuestVisitReducer,
} from './guestVisit/routes'

import {searchSlice,searchReducer} from './search/routes'

export default function s(){ return "Nothing default"}

export {
	// university profile state/slice/reducer
	universityBasicDetailsSlice,universityBasicDetailsReducer,universityBasicDetailsUpdateReducer,
	universityContactSlice,universityContactReducer,universityContactAddReducer,universityContactUpdateReducer,
	universityMeetingSlice,universityMeetingReducer,universityMeetingAddReducer,universityMeetingUpdateReducer,
	universityProgramSlice,universityProgramReducer,universityProgramAddReducer,
	universityRecentUpdateSlice,universityRecentUpdateReducer,universityRecentUpdateAddReducer,universityRecentUpdateUpdateReducer,
	universityMouContractSlice,universityMouContractReducer,universityMouContractAddReducer,universityMouContractUpdateReducer,setMouContractSliceLoading,
	universityApplicationProcessSlice,universityApplicationProcessReducer,universityApplicationProcessAddReducer,
	universityDocumentRequiredSlice,universityDocumentRequiredReducer,universityDocumentRequiredAddReducer,
	universityFinancialAgreementReducer,universityFinancialAgreementAddReducer,universityFinancialAgreementSlice,
	universityGuestVisitSlice,universityGuestVisitReducer,universityGuestVisitAddReducer,
	basicGuestVisitSlice,getAllGuestVisitReducer,guestVisitAddReducer,setRedirectFunctionGuestVisit,updateViewDetailsGuestVisit,
	singleGuestVisitSlice,getGuestVisitReducer,getMeetingsSlice,getMeetingsReducer,meetingBasicDetailsUpdateReducer,
	
	// university list
	getAllUniversitySlice,getAllUniversityReducer,setRedirectFunction,updateViewDetails,universityAddReducer,
	tagsMouMasterSlice,activateYourTagChip,deleteYourTagChip,addYourTagChip,

	forgetPasswordSlice,forgetPasswordReducer,resetPasswordReducer,

	searchSlice,searchReducer,

	// meeting master
	getAllMeetingsSlice,getAllUniversityMeetingsReducer,universityMeetingsAddReducer,setRedirectFunctionMeetings,updateViewDetailsMeetings,
}